version: 2.1

jobs:
  test_achieve_vuejs:
    docker:
      - image: circleci/node:16.17.1
        environment:
          NODE_ENV: test

    working_directory: ~/achieve_vuejs

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "~/achieve_vuejs/package.json" }}
      - run:
          name: install-packages
          command: npm install
          working_directory: ~/achieve_vuejs
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "~/achieve_vuejs/package.json" }}
      - run:
          name: test
          command: npm run test
          working_directory: ~/achieve_vuejs

workflows:
  version: 2
  test:
    jobs:
      - test_achieve_vuejs:
          filters:
            branches:
              ignore: master