name: Run rspec, rubocop

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  deploy:
    name: Deploy app to AWS
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH key
        run: |
          mkdir -p -m 700 ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/Achieve-docker-ec2
          chmod 600 ~/.ssh/Achieve-docker-ec2
      - name: Deploy
        run: |
          eval $(ssh-agent)
          ssh-add ~/.ssh/Achieve-docker-ec2
          ssh -o StrictHostKeyChecking=no -A webapp@${{ secrets.TARGET_HOSTNAME }} "cd Achieve &&
          git pull origin master &&
          ~/.rbenv/shims/bundle config --local deployment true &&
          ~/.rbenv/shims/bundle config --local without development:test &&
          ~/.rbenv/shims/bundle install &&
          RAILS_ENV=production ~/.rbenv/shims/bundle exec rails assets:precompile &&
          RAILS_ENV=production ~/.rbenv/shims/bundle exec rails db:migrate

  rspec:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    services:
      mysql:
        image: mysql:8.0.29
        ports:
          - 3306:3306
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        options: --health-cmd "mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.6

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Bundler and gem install
        run: |
          gem install bundler
          bundle install
        working-directory: ./achieve_rails

      - name: Yarn install
        run: yarn install --check-files

      - name: migrate
        run: |
          bundle exec rails db:create RAILS_ENV=test
          bundle exec rails db:migrate RAILS_ENV=test
        working-directory: ./achieve_rails

      - name: Run rspec
        run: bundle exec rspec
        working-directory: ./achieve_rails

  rubocop:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.6

      - name: Run rubocop
        run: |
          gem install rubocop
          rubocop
        working-directory: ./achieve_rails