development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV['REDIS_URL'] %>
  channel_prefix: goals_achieve_production
  allowed_request_origins:
    - https://www.goals-achieve.click
